server:
  port: 8082
  servlet:
    context-path: /skillbridge

spring:
  datasource:
#     url: "jdbc:mysql://localhost:3306/skill_bridge?createDatabaseIfNotExist=true"
    url: "jdbc:mysql://localhost:3307/skill_bridge?createDatabaseIfNotExist=true"
    username: root
    password: 123456
    #  password: 110204
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties  :
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "0/ZXdY14KhVmn651XrImaFk46is4tREEj8EyQt3jWrrE3Sy/Ym0irOlzunO00MYB"
  valid-duration: 3600 #seconds
  refreshable-duration: 360000 #seconds

